/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author germa
 */
public class ClienteSWORD extends javax.swing.JFrame implements ActionListener {

    PanelConexion panelConexion;
    PanelOntologico panelOntologico;
    PanelSword panelSword;

    /**
     * Creates new form Inicio
     */
    public ClienteSWORD() {                
        initComponents();
        
        this.setResizable(false);
        
        this.panelConexion = new PanelConexion();
        this.panelOntologico = new PanelOntologico();
        this.panelSword = new PanelSword();
        
        this.setLocationRelativeTo(null);

        contenedor.add(panelConexion);

        panelConexion.setVisible(true);
        panelOntologico.setVisible(false);
        panelSword.setVisible(false);

        deshabilitarBotones();

        btn_anterior.addActionListener(this);
        btn_siguiente.addActionListener(this);

    }

    private void deshabilitarBotones() {
        if (panelConexion.isVisible()) {
            btn_anterior.setEnabled(false);
            btn_siguiente.setEnabled(true);

        } else if (panelOntologico.isVisible()) {
            btn_anterior.setEnabled(true);
            btn_siguiente.setEnabled(true);
        } else if (panelSword.isVisible()) {
            btn_anterior.setEnabled(true);
            btn_siguiente.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depósito SWORD");
        setMinimumSize(new java.awt.Dimension(800, 600));

        contenedor.setLayout(new java.awt.BorderLayout());

        btn_anterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon("E:\\Facultad\\Proyecto 2019\\CodigoPFC\\dspaceSword-depositOntologico\\src\\main\\java\\imagenes\\flecha1.png")); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_anterior);

        btn_siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_siguiente.setIcon(new javax.swing.ImageIcon("E:\\Facultad\\Proyecto 2019\\CodigoPFC\\dspaceSword-depositOntologico\\src\\main\\java\\imagenes\\flecha2.png")); // NOI18N
        btn_siguiente.setText("Siguiente");
        btn_siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_siguiente);

        contenedor.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteSWORD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object evt = e.getSource();
        if (evt.equals(btn_anterior)) {
            if (panelSword.isVisible()) {
                panelSword.setVisible(false);
                panelOntologico.setVisible(true);
                contenedor.add(panelOntologico);
                deshabilitarBotones();
                contenedor.validate();
            } else if (panelOntologico.isVisible()) {
                panelOntologico.setVisible(false);
                panelConexion.setVisible(true);
                contenedor.add(panelConexion);
                deshabilitarBotones();
                contenedor.validate();
            }
        } else if (evt.equals(btn_siguiente)) {
            if (panelConexion.isVisible()) {
                panelConexion.setVisible(false);
                panelOntologico.setVisible(true);
                contenedor.add(panelOntologico);
                deshabilitarBotones();
                contenedor.validate();
            } else if (panelOntologico.isVisible()) {
                panelOntologico.setVisible(false);
                panelSword.setVisible(true);
                contenedor.add(panelSword);
                deshabilitarBotones();
                contenedor.validate();
            }
        }
        pack();
        setLocationRelativeTo(null);
    }
}
