/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Control.FicheroControl;
import Control.StardogControl;
import Control.SwordControl;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pogliani, German
 */
public class PanelResumen extends javax.swing.JDialog {

    String boton = "";
    StardogControl stardog;
    SwordControl sword;
    FicheroControl fichero;

    /**
     * Creates new form ResumenControl
     *
     * @param parent
     * @param modal
     * @param setea
     */
    public PanelResumen(java.awt.Frame parent, boolean modal, boolean setea) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        this.setResizable(false);
        contenido.setEditable(false);
        contenido.setLineWrap(true);
        setTitle("Resumen - Deposito Cliente");

        try {
            stardog = StardogControl.getInstancia();
            contenido.append(stardog.visualizarMetadatos());
            if (setea) {
                fichero = FicheroControl.getInstancia();
                contenido.append(fichero.visualizarFicheros());
                contenido.append("\n\nEstoy conforme: Deposito mi item?");
                //this.pack();
            } else {
                //cuando no lo llamo de PanelSwrod
                contenido.append("\n\nFin de los datos.");
            }
            btn_cancelar.setVisible(setea);
            btn_binario.setVisible(setea);
            btn_zip.setVisible(setea);
            btn_mets.setVisible(setea);            
        } catch (Exception ex) {
            Logger.getLogger(PanelResumen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public String getBoton() {
        return boton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_aceptar = new javax.swing.JButton();
        btn_binario = new javax.swing.JButton();
        btn_zip = new javax.swing.JButton();
        btn_mets = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aceptar);

        btn_binario.setText("Env. Normal");
        btn_binario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_binarioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_binario);

        btn_zip.setText("Env. Zip");
        btn_zip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zipActionPerformed(evt);
            }
        });
        jPanel1.add(btn_zip);

        btn_mets.setText("Env. con Mets");
        btn_mets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_metsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mets);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setBorder(null);

        contenido.setEditable(false);
        contenido.setBackground(new java.awt.Color(255, 255, 204));
        contenido.setColumns(20);
        contenido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contenido.setLineWrap(true);
        contenido.setRows(5);
        contenido.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane2.setViewportView(contenido);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        this.boton = "btn_aceptar";
        this.setVisible(false);
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.boton = "btn_cancelar";
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_binarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_binarioActionPerformed
        this.boton = "btn_binario";
        this.setVisible(false);

    }//GEN-LAST:event_btn_binarioActionPerformed

    private void btn_zipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zipActionPerformed
        this.boton = "btn_zip";
        this.setVisible(false);
    }//GEN-LAST:event_btn_zipActionPerformed

    private void btn_metsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_metsActionPerformed
        this.boton = "btn_mets";
        this.setVisible(false);
    }//GEN-LAST:event_btn_metsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelResumen dialog = new PanelResumen(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_binario;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_mets;
    private javax.swing.JButton btn_zip;
    private javax.swing.JTextArea contenido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
