/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.DialogWaitControl;
import Control.ConfigControl;
import Control.FicheroControl;
import Control.RestControl;
import Control.StardogControl;
import com.complexible.stardog.StardogException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;

/**
 *
 * @author
 */
public class Configurando extends javax.swing.JDialog {

    // seteo de los parametros conexión.
    private ConfigControl config = null;

    // rest api dspace
    RestControl rest = null;

    // conectar a Stardog
    StardogControl stardog = null;

    // saber si se hizo alguna modificacion en la conexion.
    public boolean conn = false;

    // 
    boolean restlogin, stardoglogin = false;

    // salia de los resultados.
    JTextArea consola;

    /**
     * Creates new form Login3
     *
     * @param parent
     * @param modal
     */
    public Configurando(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            initComponents();
            this.setTitle("Preferencias");
            this.setLocationRelativeTo(null);

            restlogin = false;
            stardoglogin = false;

            config = ConfigControl.getInstancia();
            config.setup_stardog();
            config.setup_dspace();
            config.setup_general();

            // STARDOG
            this.st_url.removeAllItems();
            this.st_url.setModel(new DefaultComboBoxModel(config.getServidores_st()));
            this.st_bd.setText(config.getBase());
            this.st_usuario.setText(config.getUserst());
            this.st_pass.setText(config.getPassst());
            stardog = StardogControl.getInstancia();
            // fin coneccion stardog

            // DSpace
            this.sw_url.removeAllItems();
            this.sw_url.setModel(new DefaultComboBoxModel(config.getServidores_rest()));
            this.sw_usuario.setText(config.getUseRest());
            this.sw_pass.setText(config.getPassRest());
            //this.sw_obo.setText(login.getObo()); // ya no aplica.
            rest = RestControl.getInstancia();
            // fin coneccion DSpace

            // General
            this.txtWorkFolder.setText(config.getFolderWork());
            this.txtHandle.setText(config.getHandle());
            // fin General                        
        } catch (IOException ex) {
            Logger.getLogger(Configurando.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Configurando.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * @param consola
     */
    public void setConsola(JTextArea consola) {
        this.consola = consola;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        panel_Superior = new javax.swing.JPanel();
        cont_stardog = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreBDStardogLabel = new javax.swing.JLabel();
        st_url = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        nombreBDStardogLabel4 = new javax.swing.JLabel();
        st_otro = new javax.swing.JTextField();
        btn_agregar_st = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userStardogLabel = new javax.swing.JLabel();
        st_usuario = new javax.swing.JTextField();
        passStardogLabel = new javax.swing.JLabel();
        st_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        nombreBDStardogLabel1 = new javax.swing.JLabel();
        st_bd = new javax.swing.JTextField();
        btnGuardarBase = new javax.swing.JButton();
        cont_sword = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nombreBDStardogLabel2 = new javax.swing.JLabel();
        sw_url = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        nombreBDStardogLabel5 = new javax.swing.JLabel();
        sw_otro = new javax.swing.JTextField();
        btn_agregar_sw = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nombreBDStardogLabel3 = new javax.swing.JLabel();
        sw_usuario = new javax.swing.JTextField();
        userStardogLabel1 = new javax.swing.JLabel();
        sw_pass = new javax.swing.JPasswordField();
        generalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtWorkFolder = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnGuardarUT = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHandle = new javax.swing.JTextField();
        btnGuardarHandle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel_inferior = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginPanel.setLayout(new java.awt.BorderLayout());

        panel_Superior.setLayout(new javax.swing.BoxLayout(panel_Superior, javax.swing.BoxLayout.Y_AXIS));

        cont_stardog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Base de Datos Gráfico - Stardog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_stardog.setLayout(new java.awt.GridLayout(4, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel.setText("URL");
        nombreBDStardogLabel.setName(""); // NOI18N
        jPanel1.add(nombreBDStardogLabel);

        st_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        st_url.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        st_url.setEditor(null);
        st_url.setFocusTraversalPolicyProvider(true);
        st_url.setMaximumSize(new java.awt.Dimension(56, 20));
        jPanel1.add(st_url);

        cont_stardog.add(jPanel1);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel4.setText("Otra URL");
        nombreBDStardogLabel4.setName(""); // NOI18N
        jPanel7.add(nombreBDStardogLabel4);

        st_otro.setColumns(50);
        st_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_otroActionPerformed(evt);
            }
        });
        jPanel7.add(st_otro);

        btn_agregar_st.setText("Agregar");
        btn_agregar_st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_stActionPerformed(evt);
            }
        });
        jPanel7.add(btn_agregar_st);

        cont_stardog.add(jPanel7);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        userStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel.setText("Usuario");
        userStardogLabel.setName(""); // NOI18N
        userStardogLabel.setPreferredSize(new java.awt.Dimension(50, 17));
        jPanel2.add(userStardogLabel);

        st_usuario.setColumns(30);
        st_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(st_usuario);

        passStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel.setText("Clave");
        passStardogLabel.setName(""); // NOI18N
        jPanel2.add(passStardogLabel);

        st_pass.setEditable(false);
        st_pass.setBackground(new java.awt.Color(255, 255, 255));
        st_pass.setColumns(30);
        st_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                st_passFocusLost(evt);
            }
        });
        st_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                st_passMouseClicked(evt);
            }
        });
        st_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_passActionPerformed(evt);
            }
        });
        jPanel2.add(st_pass);

        cont_stardog.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel1.setText("Base de datos");
        nombreBDStardogLabel1.setName(""); // NOI18N
        jPanel3.add(nombreBDStardogLabel1);

        st_bd.setColumns(30);
        st_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_bdActionPerformed(evt);
            }
        });
        jPanel3.add(st_bd);

        btnGuardarBase.setText("Guardar cambios");
        btnGuardarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarBaseActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarBase);

        cont_stardog.add(jPanel3);

        panel_Superior.add(cont_stardog);

        cont_sword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repositorio DSpace - Rest API", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_sword.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel2.setText("URL");
        nombreBDStardogLabel2.setName(""); // NOI18N
        jPanel4.add(nombreBDStardogLabel2);

        sw_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(sw_url);

        cont_sword.add(jPanel4);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel5.setText("Otra URL");
        nombreBDStardogLabel5.setName(""); // NOI18N
        jPanel8.add(nombreBDStardogLabel5);

        sw_otro.setColumns(50);
        sw_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_otroActionPerformed(evt);
            }
        });
        jPanel8.add(sw_otro);

        btn_agregar_sw.setText("Agregar");
        btn_agregar_sw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_swActionPerformed(evt);
            }
        });
        jPanel8.add(btn_agregar_sw);

        cont_sword.add(jPanel8);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel3.setText("Usuario");
        nombreBDStardogLabel3.setName(""); // NOI18N
        jPanel5.add(nombreBDStardogLabel3);

        sw_usuario.setColumns(30);
        sw_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_usuarioActionPerformed(evt);
            }
        });
        jPanel5.add(sw_usuario);

        userStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel1.setText("Clave");
        userStardogLabel1.setName(""); // NOI18N
        jPanel5.add(userStardogLabel1);

        sw_pass.setColumns(30);
        sw_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sw_passFocusLost(evt);
            }
        });
        sw_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sw_passMouseClicked(evt);
            }
        });
        sw_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_passActionPerformed(evt);
            }
        });
        jPanel5.add(sw_pass);

        cont_sword.add(jPanel5);

        panel_Superior.add(cont_sword);

        loginPanel.add(panel_Superior, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Datos de conexión", loginPanel);

        generalPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("     ");
        generalPanel.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jLabel8.setText("      ");
        generalPanel.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel7.setText("     ");
        generalPanel.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        jLabel5.setText("    ");
        generalPanel.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel17.setPreferredSize(new java.awt.Dimension(653, 200));
        jPanel17.setLayout(new java.awt.GridLayout(10, 1));

        jPanel13.setMinimumSize(new java.awt.Dimension(193, 20));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Unidad de trabajo");
        jPanel13.add(jLabel2);

        txtWorkFolder.setColumns(25);
        txtWorkFolder.setText("E:/");
        jPanel13.add(txtWorkFolder);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel13.add(btnEditar);

        btnGuardarUT.setText("Guardar cambios");
        btnGuardarUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUTActionPerformed(evt);
            }
        });
        jPanel13.add(btnGuardarUT);

        jPanel17.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Handle - web browser");
        jPanel14.add(jLabel1);

        txtHandle.setColumns(25);
        txtHandle.setText("http://localhot:8080/xmlui/handle/");
        jPanel14.add(txtHandle);

        btnGuardarHandle.setText("Guardar cambios");
        btnGuardarHandle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHandleActionPerformed(evt);
            }
        });
        jPanel14.add(btnGuardarHandle);

        jLabel3.setText("ej:  (http://localhot:8080/xmlui)");
        jPanel14.add(jLabel3);

        jPanel17.add(jPanel14);

        generalPanel.add(jPanel17, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Datos generales", generalPanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        panel_inferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        panel_inferior.add(btnConectar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel_inferior.add(btnCancelar);

        getContentPane().add(panel_inferior, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        DialogWaitControl wait = new DialogWaitControl(2);
        SwingWorker<Void, String> mySwingWorker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    conn = false;
                    //conectar a DSpace a traves de rest api
                    // seteamos las variables primero
                    publish(">> Conectando a DSpace...\n", "0");
                    config.setUri((String) sw_url.getSelectedItem());    //private String uri = "";
                    config.setUseRest(sw_usuario.getText());    //private String usesw = "";
                    config.setPassRest(new String(sw_pass.getPassword()));    //private String passw = "";
                    // conectamos
                    restlogin = rest.conectar();

                    // -----------------------------------------------------------------
                    //conectar a DSpace a traves de Stardog api
                    // seteamos las variables primero
                    config.setUrl_st((String) st_url.getSelectedItem());    //private String url = "";           
                    config.setUserst(st_usuario.getText());    //private String userst = "";
                    config.setPassst(new String(st_pass.getPassword()));    //private String passst = "";
                    config.setBase(st_bd.getText());    //private String base = "";
                    // conectar a Stardog 

                    publish(">> Conectando a Stardog...\n", "1");
                    stardog.conectar();

                    stardoglogin = stardog.estatus();

                    publish(">> Autenticación finalizada.\n", "2");
                    System.out.println("restLogin : " + restlogin);
                    System.out.println("Stardog Login : " + stardoglogin);
                    if (restlogin && stardoglogin) {
                        conn = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "La autenticación no fue correcta.", "Informe", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (StardogException ex) {
                    Logger.getLogger(Configurando.class.getName()).log(Level.SEVERE, null, ex);
                }
                wait.close();
                setVisible(false);
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                wait.incrementarProBar(Integer.parseInt(chunks.get(1)));
                consola.append(chunks.get(0));
            }
        };
        mySwingWorker.execute();
        wait.makeWait("Conectando...", evt, 0);
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.consola.append("Operación de conexión cancelada.\n");
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void st_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_otroActionPerformed

    private void btn_agregar_stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_stActionPerformed
        try {
            if (st_otro.getText().isEmpty()) {
                return;
            }
            config.grabarUrlSt(this.st_otro.getText());
            config.setup_stardog();
            this.st_url.setModel(new DefaultComboBoxModel(config.getServidores_st()));
            this.st_otro.setText("");
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_agregar_stActionPerformed

    private void st_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_usuarioActionPerformed

    private void st_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_st_passFocusLost
        st_pass.setEchoChar('\u25cf');
    }//GEN-LAST:event_st_passFocusLost

    private void st_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_passMouseClicked
        st_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_st_passMouseClicked

    private void st_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_passActionPerformed

    private void st_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_bdActionPerformed

    private void sw_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_otroActionPerformed

    private void btn_agregar_swActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_swActionPerformed
        try {
            if (sw_otro.getText().isEmpty()) {
                return;
            }
            config.grabarUriSw(this.sw_otro.getText());
            config.setup_dspace();
            this.sw_url.setModel(new DefaultComboBoxModel(config.getServidores_rest()));
            //this.sw_url.updateUI();
            this.sw_otro.setText("");
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_agregar_swActionPerformed

    private void sw_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_usuarioActionPerformed

    private void sw_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sw_passFocusLost
        sw_pass.setEchoChar('\u25cf');
    }//GEN-LAST:event_sw_passFocusLost

    private void sw_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sw_passMouseClicked
        sw_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_sw_passMouseClicked

    private void sw_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_passActionPerformed

    private void btnGuardarUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUTActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Desea Guardar?", "Confirme", JOptionPane.YES_NO_OPTION) == 1) {
            if (!txtWorkFolder.getText().isEmpty()) {
                config.grabarFolder(txtWorkFolder.getText());
                btnConectar.setEnabled(true);
            } else {
                btnConectar.setEnabled(false);
            }
        } else {
            this.txtWorkFolder.setText(config.getFolderWork());
        }

    }//GEN-LAST:event_btnGuardarUTActionPerformed

    private void btnGuardarHandleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHandleActionPerformed
        if (!txtHandle.getText().isEmpty()) {
            config.grabarHandle(txtHandle.getText());
        }
    }//GEN-LAST:event_btnGuardarHandleActionPerformed

    private void btnGuardarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarBaseActionPerformed
        try {
            if (!st_bd.getText().isEmpty()) {
                config.grabarBase(st_bd.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar cambios del nombre de la BD." + e.getMessage(),
                    "Informe",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarBaseActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        FicheroControl unFichero = FicheroControl.getInstancia();
        txtWorkFolder.setText(unFichero.getCarpeta(this).getAbsolutePath());
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configurando dialog = new Configurando(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardarBase;
    private javax.swing.JButton btnGuardarHandle;
    private javax.swing.JButton btnGuardarUT;
    private javax.swing.JButton btn_agregar_st;
    private javax.swing.JButton btn_agregar_sw;
    private javax.swing.JPanel cont_stardog;
    private javax.swing.JPanel cont_sword;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nombreBDStardogLabel;
    private javax.swing.JLabel nombreBDStardogLabel1;
    private javax.swing.JLabel nombreBDStardogLabel2;
    private javax.swing.JLabel nombreBDStardogLabel3;
    private javax.swing.JLabel nombreBDStardogLabel4;
    private javax.swing.JLabel nombreBDStardogLabel5;
    private javax.swing.JPanel panel_Superior;
    private javax.swing.JPanel panel_inferior;
    private javax.swing.JLabel passStardogLabel;
    private javax.swing.JTextField st_bd;
    private javax.swing.JTextField st_otro;
    private javax.swing.JPasswordField st_pass;
    private javax.swing.JComboBox<String> st_url;
    private javax.swing.JTextField st_usuario;
    private javax.swing.JTextField sw_otro;
    private javax.swing.JPasswordField sw_pass;
    private javax.swing.JComboBox<String> sw_url;
    private javax.swing.JTextField sw_usuario;
    private javax.swing.JTextField txtHandle;
    private javax.swing.JTextField txtWorkFolder;
    private javax.swing.JLabel userStardogLabel;
    private javax.swing.JLabel userStardogLabel1;
    // End of variables declaration//GEN-END:variables
}
