/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.LoginControl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author germa
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Coneccion
     */
      
    private LoginControl login = null; 
        
    public Login(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setResizable(false);
            this.setTitle("LogIn");
            
            login = LoginControl.getInstancia();
            
            //STARDOG            
            this.st_url.removeAllItems();
            this.st_url.setModel(new DefaultComboBoxModel(login.getServidores_st()));
            this.st_bd.setText(login.getBase());
            this.st_usuario.setText(login.getUserst());
            this.st_pass.setText(login.getPassst());
                        
            //SWORD            
            this.sw_url.removeAllItems();
            this.sw_url.setModel(new DefaultComboBoxModel(login.getServidores_sw()));
            this.sw_usuario.setText(login.getUsesw());
            this.sw_pass.setText(login.getPassw());
            this.sw_obo.setText(login.getObo());
            //...
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont_stardog = new javax.swing.JPanel();
        st_url = new javax.swing.JComboBox<>();
        nombreBDStardogLabel = new javax.swing.JLabel();
        userStardogLabel = new javax.swing.JLabel();
        st_otro = new javax.swing.JTextField();
        passStardogLabel = new javax.swing.JLabel();
        nombreBDStardogLabel1 = new javax.swing.JLabel();
        nombreBDStardogLabel4 = new javax.swing.JLabel();
        st_usuario = new javax.swing.JTextField();
        st_bd = new javax.swing.JTextField();
        st_pass = new javax.swing.JPasswordField();
        cont_sw = new javax.swing.JPanel();
        sw_url = new javax.swing.JComboBox<>();
        nombreBDStardogLabel2 = new javax.swing.JLabel();
        userStardogLabel1 = new javax.swing.JLabel();
        sw_usuario = new javax.swing.JTextField();
        passStardogLabel1 = new javax.swing.JLabel();
        sw_obo = new javax.swing.JTextField();
        nombreBDStardogLabel3 = new javax.swing.JLabel();
        sw_pass = new javax.swing.JPasswordField();
        nombreBDStardogLabel5 = new javax.swing.JLabel();
        sw_otro = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cont_stardog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STARDOG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        cont_stardog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cont_stardog.add(st_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 480, 30));

        nombreBDStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel.setText("URL");
        nombreBDStardogLabel.setName(""); // NOI18N
        cont_stardog.add(nombreBDStardogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 20));

        userStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel.setText("Usuario");
        userStardogLabel.setName(""); // NOI18N
        cont_stardog.add(userStardogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        st_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_otroActionPerformed(evt);
            }
        });
        cont_stardog.add(st_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 480, 30));

        passStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel.setText("Clave");
        passStardogLabel.setName(""); // NOI18N
        cont_stardog.add(passStardogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 40, 20));

        nombreBDStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel1.setText("BD");
        nombreBDStardogLabel1.setName(""); // NOI18N
        cont_stardog.add(nombreBDStardogLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 20, 20));

        nombreBDStardogLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel4.setText("Otro");
        nombreBDStardogLabel4.setName(""); // NOI18N
        cont_stardog.add(nombreBDStardogLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, 20));

        st_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_usuarioActionPerformed(evt);
            }
        });
        cont_stardog.add(st_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 220, 30));

        st_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_bdActionPerformed(evt);
            }
        });
        cont_stardog.add(st_bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 480, 30));
        cont_stardog.add(st_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 210, 30));

        cont_sw.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        cont_sw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sw_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cont_sw.add(sw_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 480, 30));

        nombreBDStardogLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel2.setText("URL");
        nombreBDStardogLabel2.setName(""); // NOI18N
        cont_sw.add(nombreBDStardogLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 20));

        userStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel1.setText("Clave");
        userStardogLabel1.setName(""); // NOI18N
        cont_sw.add(userStardogLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 20));

        sw_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_usuarioActionPerformed(evt);
            }
        });
        cont_sw.add(sw_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 30));

        passStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel1.setText("Mediador (On Behalf of)");
        passStardogLabel1.setName(""); // NOI18N
        cont_sw.add(passStardogLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 20));
        cont_sw.add(sw_obo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 380, 30));

        nombreBDStardogLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel3.setText("Usuario");
        nombreBDStardogLabel3.setName(""); // NOI18N
        cont_sw.add(nombreBDStardogLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 20));

        sw_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_passActionPerformed(evt);
            }
        });
        cont_sw.add(sw_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, 30));

        nombreBDStardogLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel5.setText("Otro");
        nombreBDStardogLabel5.setName(""); // NOI18N
        cont_sw.add(nombreBDStardogLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 30, 20));

        sw_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_otroActionPerformed(evt);
            }
        });
        cont_sw.add(sw_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 480, 30));

        jButton2.setText("Aceptar y conectar");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.setActionCommand("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cont_stardog, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cont_sw, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cont_stardog, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cont_sw, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void st_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_otroActionPerformed

    private void sw_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_usuarioActionPerformed

    private void sw_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_passActionPerformed

    private void sw_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_otroActionPerformed

    private void st_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_usuarioActionPerformed

    private void st_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_bdActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel cont_stardog;
    private javax.swing.JPanel cont_sw;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nombreBDStardogLabel;
    private javax.swing.JLabel nombreBDStardogLabel1;
    private javax.swing.JLabel nombreBDStardogLabel2;
    private javax.swing.JLabel nombreBDStardogLabel3;
    private javax.swing.JLabel nombreBDStardogLabel4;
    private javax.swing.JLabel nombreBDStardogLabel5;
    private java.awt.Panel panel1;
    private javax.swing.JLabel passStardogLabel;
    private javax.swing.JLabel passStardogLabel1;
    private javax.swing.JTextField st_bd;
    private javax.swing.JTextField st_otro;
    private javax.swing.JPasswordField st_pass;
    private javax.swing.JComboBox<String> st_url;
    private javax.swing.JTextField st_usuario;
    private javax.swing.JTextField sw_obo;
    private javax.swing.JTextField sw_otro;
    private javax.swing.JPasswordField sw_pass;
    private javax.swing.JComboBox<String> sw_url;
    private javax.swing.JTextField sw_usuario;
    private javax.swing.JLabel userStardogLabel;
    private javax.swing.JLabel userStardogLabel1;
    // End of variables declaration//GEN-END:variables
}
