/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.LoginControler;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author germa
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    private LoginControler login = null; 
    
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setSize(750, 350);
            this.setResizable(true);
            this.setTitle("LogIn");
            
            login = LoginControler.getInstancia();
            
            //STARDOG            
            this.st_url.removeAllItems();
            this.st_url.setModel(new DefaultComboBoxModel(login.getServidores_st()));
            this.st_bd.setText(login.getBase());
            this.st_usuario.setText(login.getUserst());
            this.st_pass.setText(login.getPassst());
            
            //SWORD            
            this.sw_url.removeAllItems();
            this.sw_url.setModel(new DefaultComboBoxModel(login.getServidores_sw()));
            this.sw_usuario.setText(login.getUsesw());
            this.sw_pass.setText(login.getPassw());
            this.sw_obo.setText(login.getObo());
            //...
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_inferior = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        panel_Superior = new javax.swing.JPanel();
        cont_stardog = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreBDStardogLabel = new javax.swing.JLabel();
        st_url = new javax.swing.JComboBox<>();
        nombreBDStardogLabel4 = new javax.swing.JLabel();
        st_otro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        userStardogLabel = new javax.swing.JLabel();
        st_usuario = new javax.swing.JTextField();
        passStardogLabel = new javax.swing.JLabel();
        st_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        nombreBDStardogLabel1 = new javax.swing.JLabel();
        st_bd = new javax.swing.JTextField();
        cont_sword = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nombreBDStardogLabel2 = new javax.swing.JLabel();
        sw_url = new javax.swing.JComboBox<>();
        nombreBDStardogLabel5 = new javax.swing.JLabel();
        sw_otro = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        nombreBDStardogLabel3 = new javax.swing.JLabel();
        sw_usuario = new javax.swing.JTextField();
        userStardogLabel1 = new javax.swing.JLabel();
        sw_pass = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        passStardogLabel1 = new javax.swing.JLabel();
        sw_obo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_inferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        jButton2.setText("Conectar");
        panel_inferior.add(jButton2);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_inferior.add(btn_cancelar);

        getContentPane().add(panel_inferior, java.awt.BorderLayout.PAGE_END);

        panel_Superior.setLayout(new javax.swing.BoxLayout(panel_Superior, javax.swing.BoxLayout.Y_AXIS));

        cont_stardog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "StarDog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_stardog.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel.setText("URL");
        nombreBDStardogLabel.setName(""); // NOI18N
        jPanel1.add(nombreBDStardogLabel);

        st_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        st_url.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        st_url.setEditor(null);
        st_url.setFocusTraversalPolicyProvider(true);
        jPanel1.add(st_url);

        nombreBDStardogLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel4.setText("Otro");
        nombreBDStardogLabel4.setName(""); // NOI18N
        jPanel1.add(nombreBDStardogLabel4);

        st_otro.setColumns(30);
        st_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_otroActionPerformed(evt);
            }
        });
        jPanel1.add(st_otro);

        cont_stardog.add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        userStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel.setText("Usuario");
        userStardogLabel.setName(""); // NOI18N
        userStardogLabel.setPreferredSize(new java.awt.Dimension(50, 17));
        jPanel2.add(userStardogLabel);

        st_usuario.setColumns(30);
        st_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(st_usuario);

        passStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel.setText("Clave");
        passStardogLabel.setName(""); // NOI18N
        jPanel2.add(passStardogLabel);

        st_pass.setColumns(30);
        jPanel2.add(st_pass);

        cont_stardog.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel1.setText("BD");
        nombreBDStardogLabel1.setName(""); // NOI18N
        jPanel3.add(nombreBDStardogLabel1);

        st_bd.setColumns(30);
        st_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_bdActionPerformed(evt);
            }
        });
        jPanel3.add(st_bd);

        cont_stardog.add(jPanel3);

        panel_Superior.add(cont_stardog);

        cont_sword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sword", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_sword.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel2.setText("URL");
        nombreBDStardogLabel2.setName(""); // NOI18N
        jPanel4.add(nombreBDStardogLabel2);

        sw_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(sw_url);

        nombreBDStardogLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel5.setText("Otro");
        nombreBDStardogLabel5.setName(""); // NOI18N
        jPanel4.add(nombreBDStardogLabel5);

        sw_otro.setColumns(30);
        sw_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_otroActionPerformed(evt);
            }
        });
        jPanel4.add(sw_otro);

        cont_sword.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel3.setText("Usuario");
        nombreBDStardogLabel3.setName(""); // NOI18N
        jPanel5.add(nombreBDStardogLabel3);

        sw_usuario.setColumns(30);
        sw_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_usuarioActionPerformed(evt);
            }
        });
        jPanel5.add(sw_usuario);

        userStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel1.setText("Clave");
        userStardogLabel1.setName(""); // NOI18N
        jPanel5.add(userStardogLabel1);

        sw_pass.setColumns(30);
        sw_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_passActionPerformed(evt);
            }
        });
        jPanel5.add(sw_pass);

        cont_sword.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        passStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel1.setText("Mediador (On Behalf of)");
        passStardogLabel1.setName(""); // NOI18N
        jPanel6.add(passStardogLabel1);

        sw_obo.setColumns(30);
        jPanel6.add(sw_obo);

        cont_sword.add(jPanel6);

        panel_Superior.add(cont_sword);

        getContentPane().add(panel_Superior, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void st_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_otroActionPerformed

    private void st_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_usuarioActionPerformed

    private void st_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_bdActionPerformed

    private void sw_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_usuarioActionPerformed

    private void sw_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_passActionPerformed

    private void sw_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_otroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel cont_stardog;
    private javax.swing.JPanel cont_sword;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nombreBDStardogLabel;
    private javax.swing.JLabel nombreBDStardogLabel1;
    private javax.swing.JLabel nombreBDStardogLabel2;
    private javax.swing.JLabel nombreBDStardogLabel3;
    private javax.swing.JLabel nombreBDStardogLabel4;
    private javax.swing.JLabel nombreBDStardogLabel5;
    private javax.swing.JPanel panel_Superior;
    private javax.swing.JPanel panel_inferior;
    private javax.swing.JLabel passStardogLabel;
    private javax.swing.JLabel passStardogLabel1;
    private javax.swing.JTextField st_bd;
    private javax.swing.JTextField st_otro;
    private javax.swing.JPasswordField st_pass;
    private javax.swing.JComboBox<String> st_url;
    private javax.swing.JTextField st_usuario;
    private javax.swing.JTextField sw_obo;
    private javax.swing.JTextField sw_otro;
    private javax.swing.JPasswordField sw_pass;
    private javax.swing.JComboBox<String> sw_url;
    private javax.swing.JTextField sw_usuario;
    private javax.swing.JLabel userStardogLabel;
    private javax.swing.JLabel userStardogLabel1;
    // End of variables declaration//GEN-END:variables
}
