/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.DialogWaitControler;
import Control.LoginControler;
import Control.RestControler;
import Control.StardogControler;
import com.complexible.stardog.StardogException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;

/**
 *
 * @author germa
 */
public class Login3 extends javax.swing.JDialog {

    private LoginControler login = null;

    // rest api dspace
    RestControler rest = null;

    // conectar a Stardog
    StardogControler stardog = null;

    // saber si se hizo alguna modificacion
    boolean conn = false;

    boolean restlogin, stardoglogin = false;

    JTextArea ta;

    /**
     * Creates new form Login3
     *
     * @param parent
     * @param modal
     * @param unTextArea
     */
    public Login3(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        

        try {
            initComponents();
            this.setLocationRelativeTo(null);

            restlogin = false;
            stardoglogin = false;

            login = LoginControler.getInstancia();

            // STARDOG
            this.st_url.removeAllItems();
            this.st_url.setModel(new DefaultComboBoxModel(login.getServidores_st()));
            this.st_bd.setText(login.getBase());
            this.st_usuario.setText(login.getUserst());
            this.st_pass.setText(login.getPassst());
            stardog = StardogControler.getInstancia();
            // fin coneccion stardog

            // DSpace
            this.sw_url.removeAllItems();
            this.sw_url.setModel(new DefaultComboBoxModel(login.getServidores_sw()));
            this.sw_usuario.setText(login.getUsesw());
            this.sw_pass.setText(login.getPassw());
            //this.sw_obo.setText(login.getObo()); // ya no aplica.
            rest = RestControler.getInstancia();
            // fin coneccion DSpace
        } catch (IOException ex) {
            Logger.getLogger(Login3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Login3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * @param ta
     */
    public void setTa(JTextArea ta) {
        this.ta = ta;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_inferior = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        panel_Superior = new javax.swing.JPanel();
        cont_stardog = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreBDStardogLabel = new javax.swing.JLabel();
        st_url = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        nombreBDStardogLabel4 = new javax.swing.JLabel();
        st_otro = new javax.swing.JTextField();
        btn_agregar_st = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userStardogLabel = new javax.swing.JLabel();
        st_usuario = new javax.swing.JTextField();
        passStardogLabel = new javax.swing.JLabel();
        st_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        nombreBDStardogLabel1 = new javax.swing.JLabel();
        st_bd = new javax.swing.JTextField();
        cont_sword = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nombreBDStardogLabel2 = new javax.swing.JLabel();
        sw_url = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        nombreBDStardogLabel5 = new javax.swing.JLabel();
        sw_otro = new javax.swing.JTextField();
        btn_agregar_sw = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nombreBDStardogLabel3 = new javax.swing.JLabel();
        sw_usuario = new javax.swing.JTextField();
        userStardogLabel1 = new javax.swing.JLabel();
        sw_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_inferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        jButton2.setText("Conectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_inferior.add(jButton2);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_inferior.add(btn_cancelar);

        getContentPane().add(panel_inferior, java.awt.BorderLayout.PAGE_END);

        panel_Superior.setLayout(new javax.swing.BoxLayout(panel_Superior, javax.swing.BoxLayout.Y_AXIS));

        cont_stardog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Base de Datos a Grafos: StarDog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_stardog.setLayout(new java.awt.GridLayout(4, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel.setText("URL");
        nombreBDStardogLabel.setName(""); // NOI18N
        jPanel1.add(nombreBDStardogLabel);

        st_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        st_url.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        st_url.setEditor(null);
        st_url.setFocusTraversalPolicyProvider(true);
        st_url.setMaximumSize(new java.awt.Dimension(56, 20));
        jPanel1.add(st_url);

        cont_stardog.add(jPanel1);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel4.setText("Otro");
        nombreBDStardogLabel4.setName(""); // NOI18N
        jPanel7.add(nombreBDStardogLabel4);

        st_otro.setColumns(50);
        st_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_otroActionPerformed(evt);
            }
        });
        jPanel7.add(st_otro);

        btn_agregar_st.setText("Agregar");
        btn_agregar_st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_stActionPerformed(evt);
            }
        });
        jPanel7.add(btn_agregar_st);

        cont_stardog.add(jPanel7);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        userStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel.setText("Usuario");
        userStardogLabel.setName(""); // NOI18N
        userStardogLabel.setPreferredSize(new java.awt.Dimension(50, 17));
        jPanel2.add(userStardogLabel);

        st_usuario.setColumns(30);
        st_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(st_usuario);

        passStardogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passStardogLabel.setText("Clave");
        passStardogLabel.setName(""); // NOI18N
        jPanel2.add(passStardogLabel);

        st_pass.setEditable(false);
        st_pass.setBackground(new java.awt.Color(255, 255, 255));
        st_pass.setColumns(30);
        st_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                st_passFocusLost(evt);
            }
        });
        st_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                st_passMouseClicked(evt);
            }
        });
        st_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_passActionPerformed(evt);
            }
        });
        jPanel2.add(st_pass);

        cont_stardog.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel1.setText("BD");
        nombreBDStardogLabel1.setName(""); // NOI18N
        jPanel3.add(nombreBDStardogLabel1);

        st_bd.setColumns(30);
        st_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_bdActionPerformed(evt);
            }
        });
        jPanel3.add(st_bd);

        cont_stardog.add(jPanel3);

        panel_Superior.add(cont_stardog);

        cont_sword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repositorio DSpace", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        cont_sword.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel2.setText("URL");
        nombreBDStardogLabel2.setName(""); // NOI18N
        jPanel4.add(nombreBDStardogLabel2);

        sw_url.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(sw_url);

        cont_sword.add(jPanel4);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel5.setText("Otro");
        nombreBDStardogLabel5.setName(""); // NOI18N
        jPanel8.add(nombreBDStardogLabel5);

        sw_otro.setColumns(50);
        sw_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_otroActionPerformed(evt);
            }
        });
        jPanel8.add(sw_otro);

        btn_agregar_sw.setText("Agregar");
        btn_agregar_sw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_swActionPerformed(evt);
            }
        });
        jPanel8.add(btn_agregar_sw);

        cont_sword.add(jPanel8);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBDStardogLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBDStardogLabel3.setText("Usuario");
        nombreBDStardogLabel3.setName(""); // NOI18N
        jPanel5.add(nombreBDStardogLabel3);

        sw_usuario.setColumns(30);
        sw_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_usuarioActionPerformed(evt);
            }
        });
        jPanel5.add(sw_usuario);

        userStardogLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStardogLabel1.setText("Clave");
        userStardogLabel1.setName(""); // NOI18N
        jPanel5.add(userStardogLabel1);

        sw_pass.setColumns(30);
        sw_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sw_passFocusLost(evt);
            }
        });
        sw_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sw_passMouseClicked(evt);
            }
        });
        sw_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_passActionPerformed(evt);
            }
        });
        jPanel5.add(sw_pass);

        cont_sword.add(jPanel5);

        panel_Superior.add(cont_sword);

        getContentPane().add(panel_Superior, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogWaitControler wait = new DialogWaitControler(2);
        SwingWorker<Void, String> mySwingWorker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    conn = false;
                    //conectar a DSpace a traves de rest api
                    // seteamos las variables primero
                    publish(">> Conectando a DSpace...\n","0");
                    login.setUri((String) sw_url.getSelectedItem());    //private String uri = "";
                    login.setUsesw(sw_usuario.getText());    //private String usesw = "";
                    login.setPassw(new String(sw_pass.getPassword()));    //private String passw = "";
                    // conectamos
                    restlogin = rest.conectar();
                    System.out.println("-------------1");                    
                    // -----------------------------------------------------------------
                    //conectar a DSpace a traves de Stardog api
                    // seteamos las variables primero
                    login.setUrl_st((String) st_url.getSelectedItem());    //private String url = "";           
                    login.setUserst(st_usuario.getText());    //private String userst = "";
                    login.setPassst(new String(st_pass.getPassword()));    //private String passst = "";
                    login.setBase(st_bd.getText());    //private String base = "";
                    // conectar a Stardog 
                    
                    publish(">> Conectando a Stardog...\n","1");
                    stardog.conectar();
                    System.out.println("-------------2");
                    stardoglogin = stardog.estatus();
                    System.out.println("-------------3");
                    publish(">> Autenticación finalizada.\n","2");
                    System.out.println("restLogin : " + restlogin);
                    System.out.println("Stardog Login : " + stardoglogin);
                    if (restlogin && stardoglogin) {
                        conn = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "La autenticación no fue correcta.", "Informe", JOptionPane.ERROR_MESSAGE);
                    }
                    setVisible(false);
                } catch (StardogException ex) {
                    Logger.getLogger(Login3.class.getName()).log(Level.SEVERE, null, ex);
                }
                wait.close();
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                wait.incrementarProBar(Integer.parseInt(chunks.get(1)));
                ta.append(chunks.get(0));                
            }

        };

        mySwingWorker.execute();
        wait.makeWait("Conectando...", evt, 0);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void st_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_otroActionPerformed

    private void btn_agregar_stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_stActionPerformed
        try {
            login.grabarUrlSt(this.st_otro.getText());
            login.setup_stardog();
            this.st_url.setModel(new DefaultComboBoxModel(login.getServidores_st()));
            //this.st_url.updateUI();
            this.st_otro.setText("");
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_agregar_stActionPerformed

    private void st_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_usuarioActionPerformed

    private void st_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_st_passFocusLost
        st_pass.setEchoChar('\u25cf');
    }//GEN-LAST:event_st_passFocusLost

    private void st_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_passMouseClicked
        st_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_st_passMouseClicked

    private void st_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_passActionPerformed

    private void st_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_bdActionPerformed

    private void sw_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_otroActionPerformed

    private void btn_agregar_swActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_swActionPerformed
        try {
            login.grabarUriSw(this.sw_otro.getText());
            login.setup_dspace();
            this.sw_url.setModel(new DefaultComboBoxModel(login.getServidores_sw()));
            //this.sw_url.updateUI();
            this.sw_otro.setText("");
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_agregar_swActionPerformed

    private void sw_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_usuarioActionPerformed

    private void sw_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sw_passFocusLost
        sw_pass.setEchoChar('\u25cf');
    }//GEN-LAST:event_sw_passFocusLost

    private void sw_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sw_passMouseClicked
        sw_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_sw_passMouseClicked

    private void sw_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sw_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login3 dialog = new Login3(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_st;
    private javax.swing.JButton btn_agregar_sw;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel cont_stardog;
    private javax.swing.JPanel cont_sword;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel nombreBDStardogLabel;
    private javax.swing.JLabel nombreBDStardogLabel1;
    private javax.swing.JLabel nombreBDStardogLabel2;
    private javax.swing.JLabel nombreBDStardogLabel3;
    private javax.swing.JLabel nombreBDStardogLabel4;
    private javax.swing.JLabel nombreBDStardogLabel5;
    private javax.swing.JPanel panel_Superior;
    private javax.swing.JPanel panel_inferior;
    private javax.swing.JLabel passStardogLabel;
    private javax.swing.JTextField st_bd;
    private javax.swing.JTextField st_otro;
    private javax.swing.JPasswordField st_pass;
    private javax.swing.JComboBox<String> st_url;
    private javax.swing.JTextField st_usuario;
    private javax.swing.JTextField sw_otro;
    private javax.swing.JPasswordField sw_pass;
    private javax.swing.JComboBox<String> sw_url;
    private javax.swing.JTextField sw_usuario;
    private javax.swing.JLabel userStardogLabel;
    private javax.swing.JLabel userStardogLabel1;
    // End of variables declaration//GEN-END:variables
}
