/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.DublinCoreControl;
import Control.ConfigControl;
import Control.RestControl;
import Modelo.BitstreamsRest;
import Modelo.ColeccionRest;
import Modelo.ComunidadRest;
import Modelo.ItemRest;
import Modelo.JLabelLink;
import Modelo.Metadato;
import Modelo.TextAreaRenderer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author germa
 */
public class Recupera extends javax.swing.JDialog {

    ComunidadRest comunidad = null;
    ColeccionRest coleccion = null;
    DefaultTableModel tree = null;

    /**
     * Creates new form Filtro
     *
     * @param parent
     * @param modal
     */
    public Recupera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int height = screenSize.height - 60;
        this.setBounds(0, 15, screenSize.width, height);
        //
        DefaultTableModel miTabla = (DefaultTableModel) tablaFiltro.getModel();
        int filas = miTabla.getRowCount();
        for (int i = 1; i <= filas; i++) {
            miTabla.removeRow(0);
        }
        //tablaFiltro.setModel(miTabla);
        //tablaFiltro.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
        //tablaFiltro.setRowHeight(50); // con 50 anda
    }

    public void setTree(TreeModel model) {
        jTree1.setModel(model);
    }

    public void setMetadatos(ListModel model) {
        jListMetadatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListMetadatos = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        norte = new javax.swing.JPanel();
        txtMetadato = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fTextLimite = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOffSet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRecursos = new javax.swing.JList<>();
        jPanel20 = new javax.swing.JPanel();
        btnDescargar = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taMetadata = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaFiltro = new javax.swing.JTable();
        panelBase = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recupero de Items.");

        panelCabecera.setPreferredSize(new java.awt.Dimension(670, 220));
        panelCabecera.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 200));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 200));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setMaximumSize(new java.awt.Dimension(492, 122));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setMaximumSize(new java.awt.Dimension(1100, 122));
        jPanel8.setMinimumSize(new java.awt.Dimension(800, 72));
        jPanel8.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 32667));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Repositorio."));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 32667));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(55, 55));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 100));

        jTree1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Repositorio");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setMaximumSize(new java.awt.Dimension(81, 100));
        jTree1.setMinimumSize(new java.awt.Dimension(55, 55));
        jTree1.setOpaque(false);
        jTree1.setPreferredSize(new java.awt.Dimension(300, 100));
        jTree1.setRequestFocusEnabled(false);
        jTree1.setVisibleRowCount(8);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel21.setText(" ");
        jPanel2.add(jLabel21, java.awt.BorderLayout.PAGE_START);

        jLabel22.setText(" ");
        jPanel2.add(jLabel22, java.awt.BorderLayout.PAGE_END);

        jLabel23.setText(" ");
        jPanel2.add(jLabel23, java.awt.BorderLayout.LINE_END);

        jLabel20.setText(" ");
        jPanel2.add(jLabel20, java.awt.BorderLayout.LINE_START);

        jPanel8.add(jPanel2);

        jPanel5.add(jPanel8);

        jTabbedPane1.addTab("Repositorio", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(532, 0));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setBackground(new java.awt.Color(0, 153, 153));
        jPanel18.setMaximumSize(new java.awt.Dimension(400, 32667));
        jPanel18.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Metadatos."));
        jScrollPane5.setOpaque(false);

        jListMetadatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListMetadatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Metadatos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListMetadatos.setOpaque(false);
        jScrollPane5.setViewportView(jListMetadatos);

        jPanel18.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jLabel25.setText(" ");
        jPanel18.add(jLabel25, java.awt.BorderLayout.LINE_START);

        jLabel26.setText(" ");
        jPanel18.add(jLabel26, java.awt.BorderLayout.PAGE_START);

        jLabel27.setText(" ");
        jPanel18.add(jLabel27, java.awt.BorderLayout.LINE_END);

        jLabel28.setText(" ");
        jPanel18.add(jLabel28, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jPanel18);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setMaximumSize(new java.awt.Dimension(400, 32667));
        jPanel10.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("   ");
        jPanel10.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("     ");
        jPanel10.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("     ");
        jPanel10.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setText("     ");
        jPanel10.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.BorderLayout());

        norte.setOpaque(false);
        norte.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtMetadato.setColumns(30);
        txtMetadato.setText("dato");
        norte.add(txtMetadato);

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        norte.add(jButton4);

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        norte.add(jButton1);

        jPanel12.add(norte, java.awt.BorderLayout.NORTH);

        center.setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo filtro", "Valor"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        center.add(jScrollPane3);

        jPanel12.add(center, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel10);

        jTabbedPane1.addTab("Metadatos", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 0));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("     ");
        jPanel7.add(jLabel9, java.awt.BorderLayout.WEST);

        jLabel11.setText("    ");
        jPanel7.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Límite: ");
        jPanel14.add(jLabel5);

        fTextLimite.setColumns(10);
        fTextLimite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        fTextLimite.setText("100");
        jPanel14.add(fTextLimite);

        jLabel7.setText("   ");
        jPanel14.add(jLabel7);

        jLabel10.setText("Offset: ");
        jPanel14.add(jLabel10);

        txtOffSet.setColumns(10);
        txtOffSet.setText("0");
        jPanel14.add(txtOffSet);

        jPanel7.add(jPanel14, java.awt.BorderLayout.CENTER);

        jLabel6.setText(" ");
        jPanel7.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel8.setText("     ");
        jPanel7.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Limites", jPanel7);

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("   ");
        jPanel16.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jLabel17.setText("   ");
        jPanel16.add(jLabel17, java.awt.BorderLayout.PAGE_END);

        jLabel18.setText("     ");
        jPanel16.add(jLabel18, java.awt.BorderLayout.LINE_START);

        jLabel19.setText("     ");
        jPanel16.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel33.setText("Repositorio DSpace en el navegador:");
        jPanel4.add(jLabel33);

        jPanel17.add(jPanel4);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel29.setText("- Reporte avanzado.");
        jPanel1.add(jLabel29);

        jLabel30.setText("Aqui.");
        jLabel30.setToolTipText("Haga click para ir a reporte.");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel1.add(jLabel30);

        jPanel17.add(jPanel1);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel31.setText("- Filtro avanzado.");
        jPanel3.add(jLabel31);

        jLabel32.setText("Aqui.");
        jLabel32.setToolTipText("Haga click para ir a filtrado.");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        jPanel3.add(jLabel32);

        jPanel17.add(jPanel3);

        jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Búsqueda avanzada", jPanel16);

        panelCabecera.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(new java.awt.Color(204, 255, 204));
        panelSur.setAutoscrolls(true);
        panelSur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton3.setText("Ejecutar filtro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelSur.add(jButton3);

        panelCabecera.add(panelSur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelCabecera, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(204, 255, 204));
        panelCentral.setPreferredSize(new java.awt.Dimension(600, 290));
        panelCentral.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel15.setText("     ");
        jPanel15.add(jLabel15);

        jLabel16.setText("Resultados");
        jPanel15.add(jLabel16);

        panelCentral.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jLabel13.setText("   ");
        panelCentral.add(jLabel13, java.awt.BorderLayout.LINE_START);

        jLabel14.setText("   ");
        panelCentral.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jPanel24.setOpaque(false);
        jPanel24.setPreferredSize(new java.awt.Dimension(800, 280));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jPanel27.setOpaque(false);
        jPanel27.setPreferredSize(new java.awt.Dimension(893, 200));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel26.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel26.setOpaque(false);
        jPanel26.setPreferredSize(new java.awt.Dimension(600, 180));
        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(350, 200));
        jPanel9.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel9.setName(""); // NOI18N
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setOpaque(false);
        jPanel25.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Recursos del ítem."));
        jScrollPane2.setMaximumSize(new java.awt.Dimension(500, 150));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 100));

        listaRecursos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        listaRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaRecursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "material" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRecursos.setMaximumSize(new java.awt.Dimension(500, 150));
        listaRecursos.setPreferredSize(new java.awt.Dimension(300, 100));
        listaRecursos.setVisibleRowCount(6);
        jScrollPane2.setViewportView(listaRecursos);

        jPanel25.add(jScrollPane2);

        jPanel9.add(jPanel25);

        jPanel20.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel20.setOpaque(false);
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDescargar.setText("Descargar recurso");
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });
        jPanel20.add(btnDescargar);

        jPanel9.add(jPanel20);

        jPanel26.add(jPanel9);

        jPanel23.setOpaque(false);
        jPanel23.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Metadatos descriptivos."));
        jScrollPane6.setOpaque(false);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(180, 50));

        taMetadata.setEditable(false);
        taMetadata.setColumns(95);
        taMetadata.setLineWrap(true);
        taMetadata.setRows(6);
        taMetadata.setText("metadatos");
        taMetadata.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        taMetadata.setMaximumSize(new java.awt.Dimension(32267, 32267));
        taMetadata.setMinimumSize(new java.awt.Dimension(50, 50));
        taMetadata.setPreferredSize(new java.awt.Dimension(600, 120));
        jScrollPane6.setViewportView(taMetadata);

        jPanel23.add(jScrollPane6);

        jPanel26.add(jPanel23);

        jPanel27.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 5));

        jButton6.setText("Examinar ìtem");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton6);

        jPanel27.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel27, java.awt.BorderLayout.PAGE_END);

        jPanel22.setPreferredSize(new java.awt.Dimension(452, 50));
        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(452, 30));

        tablaFiltro.setAutoCreateRowSorter(true);
        tablaFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro.", "Identificador ítem", "Colección", "Handle", "Titulo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFiltro.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tablaFiltro.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaFiltro.setShowVerticalLines(false);
        tablaFiltro.getTableHeader().setReorderingAllowed(false);
        tablaFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaFiltroMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tablaFiltro);
        if (tablaFiltro.getColumnModel().getColumnCount() > 0) {
            tablaFiltro.getColumnModel().getColumn(0).setMinWidth(60);
            tablaFiltro.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaFiltro.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        jPanel22.add(jScrollPane4);

        jPanel24.add(jPanel22, java.awt.BorderLayout.CENTER);

        panelCentral.add(jPanel24, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        panelBase.setBackground(new java.awt.Color(204, 204, 204));
        panelBase.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelBase.add(jButton2);

        getContentPane().add(panelBase, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RestControl rest = RestControl.getInstancia();
        rest.miFiltro(coleccion, evt, tablaFiltro, jTable1,
                Integer.parseInt(fTextLimite.getText()), Integer.parseInt(txtOffSet.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed

    }//GEN-LAST:event_jTree1MousePressed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        TreePath path = evt.getPath();
        Object[] nodos = path.getPath();

        // Mirando el ultimo nodo del path, sabemos qué nodo en concreto
        // se ha seleccionado.
        DefaultMutableTreeNode ultimoNodo
                = (DefaultMutableTreeNode) nodos[nodos.length - 1];

        if (ultimoNodo.isLeaf() && ultimoNodo.getUserObject() instanceof ColeccionRest) {
            this.coleccion = (ColeccionRest) ultimoNodo.getUserObject();
        } else {
            this.coleccion = null;
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            DublinCoreControl dublinCore = DublinCoreControl.getInstancia();
            if ((jListMetadatos.getSelectedIndex() >= 0) && !txtMetadato.getText().isEmpty()) {
                Metadato mt = (Metadato) ((Object) jListMetadatos.getSelectedValue());
                String equivalente = (String) dublinCore.getEquivalenciaDC(mt.getTipo().toLowerCase().trim());
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.addRow(new Object[]{equivalente, txtMetadato.getText()});
            }
        } catch (Exception ex) {
            Logger.getLogger(Recupera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            txtMetadato.setText((String) jTable1.getValueAt(row, 1));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void tablaFiltroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFiltroMousePressed
        try {
            RestControl rest = RestControl.getInstancia();
            DefaultTableModel miTabla = (DefaultTableModel) tablaFiltro.getModel();
            int fila = tablaFiltro.rowAtPoint(evt.getPoint());
            int columna = tablaFiltro.columnAtPoint(evt.getPoint());            
            if ((fila >= 0) && (columna >= 0)) {
                String unNombre = miTabla.getValueAt(fila, 4).toString().trim();
                String unLink = miTabla.getValueAt(fila, 1).toString().trim();                
                ItemRest miItem = new ItemRest(unNombre, unLink);                
                rest.obtenerBitstreams(miItem, listaRecursos);
                // Mostramos los metadatas.
                rest.obtenerMetadata(miItem, taMetadata);
                taMetadata.setCaretPosition(0);
            }
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Recupera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaFiltroMousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        RestControl rest = RestControl.getInstancia();
        int fila = tablaFiltro.getSelectedRow();
        int colu = tablaFiltro.getSelectedColumn();
        if ((fila >= 0) && (colu >= 0)) {
            System.out.println("Fila: " + fila + " - Columna: " + colu);
            //int fila = tablaFiltro.rowAtPoint(evt.getPoint());
            //int columna = tablaFiltro.columnAtPoint(evt.getPoint());
            String unHandle = tablaFiltro.getModel().getValueAt(fila, 3).toString().trim();
            rest.miHandle(fila, colu, unHandle);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        try {
            ConfigControl login = ConfigControl.getInstancia();
            if (listaRecursos.getModel().getSize() > 0) {
                if (!(((Object) listaRecursos.getSelectedValue()) instanceof BitstreamsRest)) {
                    return;
                }
                BitstreamsRest bs = (BitstreamsRest) ((Object) listaRecursos.getSelectedValue());
                String dir = login.getUri().trim() + bs.getLink() + "/retrieve";
                System.out.println("Recuso: " + dir);
                Runtime.getRuntime().exec("cmd.exe /c start chrome " + dir);
            } else {
                JOptionPane.showMessageDialog(this, "No Hay Recurso seleccionado.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Recupera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDescargarActionPerformed

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        jLabel32.setForeground(Color.red);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        jLabel32.setForeground(Color.black);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        jLabel30.setForeground(Color.red);
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        jLabel30.setForeground(Color.black);
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        try {
            ConfigControl config = ConfigControl.getInstancia();
            // creamos el link query
            String reporte = config.getUri().trim() + config.getReporte().trim();
            Runtime.getRuntime().exec("cmd.exe /c start chrome " + reporte);
        } catch (IOException ex) {
            Logger.getLogger(Recupera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        try {
            ConfigControl config = ConfigControl.getInstancia();
            String filtro = config.getUri().trim() + config.getFiltro().trim();
            Runtime.getRuntime().exec("cmd.exe /c start chrome " + filtro);
        } catch (IOException ex) {
            Logger.getLogger(Recupera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recupera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recupera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recupera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recupera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Recupera dialog = new Recupera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargar;
    private javax.swing.JPanel center;
    private javax.swing.JFormattedTextField fTextLimite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListMetadatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> listaRecursos;
    private javax.swing.JPanel norte;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTextArea taMetadata;
    private javax.swing.JTable tablaFiltro;
    private javax.swing.JTextField txtMetadato;
    private javax.swing.JTextField txtOffSet;
    // End of variables declaration//GEN-END:variables
}
